### ISSUE TITLE
mysql2 的引用

### ISSUE THREAD

**Issue by azole** [h221391ba/node-workshop#3]
crawler-db-HW2.js 

const mysql = require('mysql2');

放在第 5 行跟第 46 行的差別是？

**Comment by h221391ba** [comment]
我是參考文件使用方式去使mysql2的]promise，我改了一下提交了。

**Comment by azole** [comment]
這個有 push 到嗎？

**Comment by h221391ba** [comment]
原本有推，但左思右想覺得原本那樣不太好所以我把它改到了比較正常的位置，最新版本已經推嘍~
[crawler/crawler-db-HW2.js](https://github.com/h221391ba/node-workshop/blob/crawler/crawler/crawler-db-HW2.js)
經過測試表面上看起來是OK了，謝謝老師。
