### ISSUE TITLE
connection.connect at crawler-db-HW2.js

### ISSUE THREAD

**Issue by azole** [h221391ba/node-workshop#4]
https://github.com/h221391ba/node-workshop/blob/26b574c3041637263f7c3f643f85cd248e23237c/crawler/crawler-db-HW2.js#L55

這裡是不是也可以用 await 版，畢竟都用了 mysql2 了?

**Comment by h221391ba** [comment]
我就滿疑惑為什麼要mysql2要這樣用，現在明白了，之前多此一舉。
