### ISSUE TITLE
改用 connection.query

### ISSUE THREAD

**Issue by azole** [h221391ba/node-workshop#5]
https://github.com/h221391ba/node-workshop/blob/26b574c3041637263f7c3f643f85cd248e23237c/crawler/crawler-db-HW2.js#L75

你改用 connection.query 試試看，我查到是說在 mysql2，用 query 才可以支援多筆資料的 insert 之類的，你試試看？

**Comment by h221391ba** [comment]
我好像有查到但就是改了A地方沒改B所以一職沒試成功，除了看到英文直接變文盲外，找問題也是挺瞎的，謝謝老師協助，已經完成了。
